// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhjJ6zfI1-MNZfPTiQ6mqZxahET_0FaGk',
    appId: '1:671478166330:web:fc70e9182d7e36d5461603',
    messagingSenderId: '671478166330',
    projectId: 'anki-ai-web',
    authDomain: 'anki-ai-web.firebaseapp.com',
    storageBucket: 'anki-ai-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmQRU94zdlxORNpWLI8srePf01vvRIAu4',
    appId: '1:671478166330:android:4a297790256d64a1461603',
    messagingSenderId: '671478166330',
    projectId: 'anki-ai-web',
    storageBucket: 'anki-ai-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9GojSgkLbLvi87cXj4bZBxirRv6R4Qaw',
    appId: '1:671478166330:ios:a0f44caf867db577461603',
    messagingSenderId: '671478166330',
    projectId: 'anki-ai-web',
    storageBucket: 'anki-ai-web.firebasestorage.app',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9GojSgkLbLvi87cXj4bZBxirRv6R4Qaw',
    appId: '1:671478166330:ios:a0f44caf867db577461603',
    messagingSenderId: '671478166330',
    projectId: 'anki-ai-web',
    storageBucket: 'anki-ai-web.firebasestorage.app',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhjJ6zfI1-MNZfPTiQ6mqZxahET_0FaGk',
    appId: '1:671478166330:web:5825cec6e34fa004461603',
    messagingSenderId: '671478166330',
    projectId: 'anki-ai-web',
    authDomain: 'anki-ai-web.firebaseapp.com',
    storageBucket: 'anki-ai-web.firebasestorage.app',
  );
}
